### ISSUE TITLE
Tesla device app - expecting ')', found '}' @ line 98, column 13.

### ISSUE THREAD

**Issue by 4rsfed** [apwelsh/hubitat#11]
Hubitat will not accept the driver code for tesla.groovy

`expecting ')', found '}' @ line 98, column 13.`

**Comment by apwelsh** [comment]
This has not been released. The driver is being co-developed by a friend of mine and myself, as I do not own a Tesla to test with.  I know there are bugs which i will upload the fixes for. I just need to get the other changes to be merged with my changes. Since you found this, I will try to get it done quickly.

**Comment by 4rsfed** [comment]
I have a tesla, and am happy to help :) 
Trent's version did work, but I deleted it since yours was newer.

**Comment by apwelsh** [comment]
My version was created to solve a few specific things: when the car leaves a certain distance from hone, it enters away mode (as a presence sensor) and the update get less aggressive the further from home you are, based on travel speed. This is used to auto-close a garage door as one leaves home, and auto-open as one approaches home. But is also used to schedule charging for off peak hours or when batteries go below a certain threshold.
