### ISSUE TITLE
Tesla Connect Credentials?

### ISSUE THREAD

**Issue by trush44** [apwelsh/hubitat#14]
I'm not seeing my vehicle in the dropdown (the dropdown is empty). The configuration guide here notes to "enter your Tesla Connect credentials". However, the setup page itself says that Email and Password are "no longer used - enter anything!".

So I am confused...how do I configure my credentials or the login so that my car will appear in the dropdown in the next page?

**Comment by apwelsh** [comment]
This is a one-off fork of another version that I created for a friend to make it location aware. This project is dead for me, because Tesla locked us out of the system.  There are other Tesla solutions that require a computer to login and manage the auto tokens.  Then the HE system uses those tokens to sign in.

It really is too much work to deal with closed system like Tesla, since they are constantly closing out access to their system. Every time a new method is found to integrate, they revoke it.  it's a cat and mouse game I just don't have the time to play.

I leave this here in case anyone want to borrow the code for their own solutions.

**Comment by trush44** [comment]
fair enough, thanks for sharing the effort!
