### ISSUE TITLE
Hue zones throw an error during creation

### ISSUE THREAD

**Issue by xxKeoxx** [apwelsh/hubitat#17]
When I add my hue zones as groups they throw this error

`app:4502022-01-10 08:40:56.698 pm errorjava.lang.NullPointerException: Cannot invoke method refresh() on null object
app:4502022-01-10 08:40:56.640 pm debuggetDeviceState received data: [name:Front Path Lights, lights:[24, 20], sensors:[], type:Zone, state:[all_on:true, any_on:true], recycle:false, class:Downstairs, action:[on:true, bri:254, hue:7209, sat:0, effect:none, xy:[0.3804, 0.3768], ct:247, alert:select, colormode:hs]]
app:4502022-01-10 08:40:56.489 pm debugURL: https://192.168.1.37:443/api/RIZarKTw2VU66axzbYxS8r3SydYqe4FYp2nw36v4//groups/18
app:4502022-01-10 08:40:56.378 pm debuggetDeviceState received data: [name:Front Path Lights, lights:[24, 20], sensors:[], type:Zone, state:[all_on:true, `

The device is created but I’m having issues with rule machine turning those zones off.  It could be a rule machine problem but these are the only devices that have that issue.

**Comment by apwelsh** [comment]
Q: is the hue hub device still installed?? The refresh command is provided by the hue hub device. The null on refresh suggests the hub device may not be installed, or the He hub has experienced another breaking change... rare but it has happened twice where certain groovy style syntax breaks and I have to use Java based calls.  I am not seeing the error in my logs, but I will try adding a zone and room tomorrow to see if this happens to me.

**Comment by apwelsh** [comment]
Issue reproduced.  Expect update soon.

**Comment by apwelsh** [comment]
I fixed the issue with added groups.  The issue was purely cosmetic, in that after adding the group, the code issues a refresh on the group however, I failed to capture the newly created group in that update.  This was the last step in creating the group, so even though the group creation reported an error, the group is still fully functional.

Please provide more details about your rule machine error.  it may be a rule issue, but it may be another piece of code on my end.  I would like to reproduce the rule if you are willing to share.

**Comment by xxKeoxx** [comment]
I removed and re-created the rule.  The problem I was having is no longer happening.  I think there must have been an artifact from using the Hubitat HUE integration and switching over to this one.  The devices seemed to work fine but the off event in the rule wasn't working.
